import type { ExportOptions } from '@bpmn-app/shared';

/**
 * Export service handles PDF, PNG, and SVG generation.
 *
 * PDF generation uses Puppeteer server-side for branded output.
 * PNG/SVG generation can be handled client-side, but this service
 * provides a server-side fallback for automated/batch exports.
 */

interface ExportResult {
  buffer: Buffer;
  contentType: string;
  filename: string;
}

/**
 * Generate a branded PDF from BPMN XML.
 *
 * Uses Puppeteer to render the diagram in a headless browser with
 * branded header/footer, cover page, and legend.
 *
 * NOTE: Puppeteer is loaded dynamically to avoid bundling Chromium
 * in environments that don't need PDF export.
 */
export async function exportToPdf(
  bpmnXml: string,
  options: ExportOptions
): Promise<ExportResult> {
  // Dynamic import — Puppeteer is an optional dependency
  const puppeteer = await import('puppeteer').catch(() => null);

  if (!puppeteer) {
    throw new Error(
      'Puppeteer is not installed. Install it with: npm install puppeteer'
    );
  }

  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });

  try {
    const page = await browser.newPage();
    const orientation = options.orientation ?? 'landscape';
    const paperSize = options.paperSize ?? 'A3';

    // Build an HTML page that loads bpmn-js Viewer and renders the diagram
    const html = buildExportHtml(bpmnXml, options);
    await page.setContent(html, { waitUntil: 'networkidle0' });

    // Wait for bpmn-js to finish rendering
    await page.waitForSelector('.bjs-container', { timeout: 10000 });

    const pdfBuffer = await page.pdf({
      format: paperSize,
      landscape: orientation === 'landscape',
      printBackground: true,
      margin: { top: '20mm', bottom: '20mm', left: '15mm', right: '15mm' },
    });

    return {
      buffer: Buffer.from(pdfBuffer),
      contentType: 'application/pdf',
      filename: `process-map-${Date.now()}.pdf`,
    };
  } finally {
    await browser.close();
  }
}

/**
 * Build the HTML page used for PDF rendering.
 * Includes branded header, BPMN diagram, and optional legend.
 */
function buildExportHtml(bpmnXml: string, options: ExportOptions): string {
  const companyName = options.branding?.companyName ?? '';
  const primaryColor = options.branding?.primaryColor ?? '#1e40af';

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    @page { margin: 0; }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', system-ui, sans-serif; }

    .header {
      padding: 20px 30px;
      border-bottom: 3px solid ${primaryColor};
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    .header h1 {
      color: ${primaryColor};
      font-size: 18px;
    }
    .header .date {
      color: #6b7280;
      font-size: 12px;
    }

    .diagram-container {
      width: 100%;
      height: calc(100vh - 100px);
      padding: 10px;
    }
    .bjs-container { width: 100%; height: 100%; }

    .footer {
      position: fixed;
      bottom: 0;
      width: 100%;
      padding: 10px 30px;
      border-top: 1px solid #e5e7eb;
      font-size: 10px;
      color: #9ca3af;
      display: flex;
      justify-content: space-between;
    }
  </style>
  <script src="https://unpkg.com/bpmn-js@18/dist/bpmn-navigated-viewer.production.min.js"></script>
</head>
<body>
  <div class="header">
    <h1>${companyName}</h1>
    <span class="date">${new Date().toLocaleDateString()}</span>
  </div>
  <div class="diagram-container">
    <div id="canvas" class="bjs-container"></div>
  </div>
  <div class="footer">
    <span>${options.branding?.footerText ?? ''}</span>
    <span>Generated by BPMN Process Mapper</span>
  </div>
  <script>
    const viewer = new BpmnJS({ container: '#canvas' });
    const xml = ${JSON.stringify(bpmnXml)};
    viewer.importXML(xml).then(() => {
      viewer.get('canvas').zoom('fit-viewport');
    });
  </script>
</body>
</html>`;
}

/**
 * Export BPMN to SVG (server-side via Puppeteer).
 */
export async function exportToSvg(bpmnXml: string): Promise<ExportResult> {
  const puppeteer = await import('puppeteer').catch(() => null);
  if (!puppeteer) {
    throw new Error('Puppeteer is not installed.');
  }

  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });

  try {
    const page = await browser.newPage();
    const html = `<!DOCTYPE html>
<html><head>
<script src="https://unpkg.com/bpmn-js@18/dist/bpmn-navigated-viewer.production.min.js"></script>
</head><body>
<div id="canvas" style="width:2000px;height:1200px"></div>
<script>
  const viewer = new BpmnJS({ container: '#canvas' });
  viewer.importXML(${JSON.stringify(bpmnXml)}).then(() => {
    viewer.get('canvas').zoom('fit-viewport');
    return viewer.saveSVG();
  }).then(({ svg }) => {
    document.getElementById('svg-output').textContent = svg;
  });
</script>
<pre id="svg-output" style="display:none"></pre>
</body></html>`;

    await page.setContent(html, { waitUntil: 'networkidle0' });
    await page.waitForSelector('.bjs-container', { timeout: 10000 });

    const svgContent = await page.$eval('#svg-output', (el) => el.textContent ?? '');

    return {
      buffer: Buffer.from(svgContent, 'utf-8'),
      contentType: 'image/svg+xml',
      filename: `process-map-${Date.now()}.svg`,
    };
  } finally {
    await browser.close();
  }
}
